name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI Android Workload
        run: dotnet workload install maui-android

      - name: Clean bin/obj
        run: rm -rf bin obj

      - name: Restore dependencies
        run: dotnet restore

      - name: Build APK (Release)
        run: dotnet publish -f:net8.0-android -c:Release -p:AndroidPackageFormat=apk

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ColorFallPuzzle-APK
          path: bin/Release/net8.0-android/publish/*.apk

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: bin/Release/net8.0-android/publish/*.apk
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
